server:
#  servlet:
#    context-path: /zhouBao
  port: 8086

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url : jdbc:mysql://localhost:3306/zhoubao?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 2
    max-active: 5
    max-wait : 3000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password: Znnj2020
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
#  config-location: classpath:mybatis-config.xml